name: Build Windows EXE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OS dependencies for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev libpixman-1-dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build executable for Windows
        run: pkg . --targets node14-win-x64 --output paintbynumbersgenerator-win.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: paintbynumbersgenerator-win
          path: paintbynumbersgenerator-win.exe
