name: CLI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install GTK dependencies
        run: |
          choco install gtk-runtime pkgconfiglite -y

      - name: Set PKG_CONFIG_PATH for GTK
        run: echo "PKG_CONFIG_PATH=C:\GTK\lib\pkgconfig" >> $GITHUB_ENV

      - name: Add GTK bin to PATH
        run: echo "C:\GTK\bin" >> $GITHUB_PATH

      - name: Set environment variable for Visual Studio for node-gyp
        run: echo "GYP_MSVS_VERSION=2022" >> $GITHUB_ENV

      - name: Install dependencies from package-lock.json
        run: npm ci

      - name: Install pkg globally
        run: npm install pkg -g

      - name: Install TypeScript globally
        run: npm install typescript -g

      - name: Build CLI to JavaScript
        working-directory: ./src-cli
        run: tsc

      - name: Package CLI to single executable
        run: pkg .

      - name: Create output directory
        run: mkdir "out"

      - name: Copy binary to out directory
        run: copy paint-by-numbers-generator-win.exe .\out\paint-by-numbers-generator-win.exe

      - name: Copy node-canvas binaries to output
        run: copy .\node_modules\canvas\build\Release\* .\out

      - name: Cleanup unnecessary debug files
        working-directory: ./out
        run: del *.pdb *.ipdb *.iobj

      - name: Upload out as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pbn-cli-win
          path: .\out\*
        env:
          CI: true

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Download a Build Artifact zip
        uses: actions/download-artifact@v4
        with:
          name: "pbn-cli-win"
          path: "./artifacts/pbn-cli-win.zip"

      - name: Create development prerelease
        uses: ncipollo/release-action@v1
        with:
          artifact: "artifacts/*"
          prerelease: true
          allowUpdates: true
          name: "CLI Development build"
          tag: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
